- firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 10250/udp
    permanent: yes
    state: enabled
    immediate: yes
- name: Enable firewalld
  service: name=firewalld state=started enabled=yes

- name: allow_tcp_port_6443
  iptables: 
    chain: INPUT
    protocol: tcp
    destination_port: 6443
    ctstate: NEW
    jump: ACCEPT
    comment: Accept connections on port 6443
- name: allow_tcp_port_10250
  iptables: 
    chain: INPUT
    protocol: tcp
    destination_port: 10250
    ctstate: NEW
    jump: ACCEPT
    comment: Accept connections on port 6443
- name: allow_tcp_port_80
  iptables: 
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW
    jump: ACCEPT
    comment: Accept connections on port 6443
- name: allow_tcp_port_8080
  iptables: 
    chain: INPUT
    protocol: tcp
    destination_port: 8080
    ctstate: NEW
    jump: ACCEPT
    comment: Accept connections on port 6443

- name: Sets enforce
  shell: setenforce 0
- name: Disable SELinux
  selinux:
    state: disabled

- name: set timezone
  shell: timedatectl set-timezone Europe/Dublin
- name: Copy over the NTP configuration
  template: src=./templates/ntp.conf dest=/etc/ntp.conf
  notify:
  - restart ntpd
  tags: ntp
- name: Make sure NTP is stopped
  service: name=ntpd state=stopped enabled=yes
  tags: ntp
- name: Sync time initialy
  shell: ntpdate 172.26.138.141
  tags: ntp
- name: Make sure NTP is started up
  service: name=ntpd state=started enabled=yes
  tags: ntp
- name: Sync hwclock
  shell: hwclock -w
  tags: ntp

- name: Update hosts file
  blockinfile:
    path: /etc/hosts
    create: yes
    block: |
      {% for item in ansible_play_batch %}
      {{ hostvars[item].ansible_ssh_host }}   {{ item }}
      {% endfor %}